### ISSUE TITLE
Set up base of site

### ISSUE THREAD

**Issue by sokkit** [sokkit/tournament_site#3]
#### Tasks
- [x] Create Flask Server
- [x] Create base html pages
- [x] Add libraries: bootstrap, react, jinjja, jquery
- [x] Set up template for jinja

#### Acceptance Criteria
- Libraries are added with no errors
- Server will display page on local host
