### ISSUE TITLE
Style tournament page

### ISSUE THREAD

**Issue by sokkit** [sokkit/tournament_site#8]
#### Tasks
- [x] Use JS to number columns
- [x] Distinguish the two tables
- [x] Add tournament name
- [ ] Add more styling to tables

#### Acceptance Criteria
- Acceptance criteria 1
